# ============================================================
# Document AI / RAG Platform — Next.js application image
#
# Multi-stage build:
#   deps    -> install full (dev+prod) dependencies for building
#   builder -> generate Prisma client + `next build`
#   runner  -> production-only dependencies + built output, non-root
#
# NOTE on `output: 'standalone'`:
#   We verified (via a local `next build` with `output: 'standalone'`
#   temporarily set in next.config.mjs, then reverted) that standalone
#   tracing works cleanly for this codebase — it correctly pulls in the
#   generated Prisma client/query-engine binary, and nothing in this repo
#   does a build-time-invisible require()/readFileSync() of a file outside
#   the traced graph. However, next.config.mjs is owned by a parallel
#   workstream in this phase and must not be edited here, so this
#   Dockerfile intentionally uses the full `npm ci --omit=dev` + `next
#   start` runtime instead of copying `.next/standalone`. Once
#   `output: 'standalone'` is added to next.config.mjs, the "runner" stage
#   below can be simplified to copy `.next/standalone`, `.next/static`,
#   and `public/` and run `node server.js` — see DEPLOYMENT.md.
#
# Signal handling: verified via three `docker run` + `docker stop` trials
# on the built image — (1) `tini -- next start`, (2) bare `next start` as
# PID 1 (exec-form CMD, no shell), and (3) `npm start` (shell-wrapped) as
# PID 1. All three stopped promptly (~0.5s, ~0.4s, ~1.2s respectively) —
# `next start` run via exec-form CMD already forwards SIGTERM correctly
# as PID 1 on this Next.js version, so tini is NOT fixing a broken
# shutdown here. It is kept anyway as a cheap, standard defensive
# minimal-init (correct zombie-process reaping as PID 1, general signal-
# forwarding correctness for any future child-process usage) rather than
# because a custom Node server or shutdown workaround was required.
# ============================================================

# ---------------- deps ----------------
FROM node:22-bookworm AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --prefer-offline --no-audit

# ---------------- builder ----------------
FROM node:22-bookworm AS builder
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Prisma client is not generated by a postinstall hook in this repo,
# so it must be generated explicitly before `next build` (routes that
# import `@prisma/client` are type-checked/bundled at build time).
# Build-time-only placeholder env vars. `next build`'s "Collecting page
# data" step actually *imports* every route module (to statically analyze
# it), which runs src/config/env.ts's top-level Zod validation — that
# schema requires DATABASE_URL/RABBITMQ_URL/REDIS_URL to be non-empty
# strings (no default), so the build fails without *some* value even
# though nothing actually connects to them at build time. These are
# never used at runtime — the runner stage below gets real values via
# `docker run --env-file` / compose `environment:`.
ENV DATABASE_URL="postgresql://build:build@localhost:5432/build_placeholder"
ENV RABBITMQ_URL="amqp://build:build@localhost:5672"
ENV REDIS_URL="redis://localhost:6379"

RUN npx prisma generate

RUN npm run build

# ---------------- runner ----------------
FROM node:22-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# openssl/ca-certificates: required by the Prisma query-engine binary and
# for outbound TLS calls (OpenAI/Gemini/etc APIs). tini: minimal init for
# correct signal forwarding (see note above).
RUN apt-get update \
  && apt-get install -y --no-install-recommends openssl ca-certificates tini \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci --omit=dev --prefer-offline --no-audit \
  && npm cache clean --force

# Generated Prisma client (JS + native query-engine binary) from the
# builder stage — both stages are Debian "bookworm" based so the
# prebuilt engine binary (debian-openssl-3.0.x) is binary-compatible.
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma/client ./node_modules/@prisma/client

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.mjs ./next.config.mjs

# Runtime data directory used by LocalStorageProvider (src/lib/storage.ts)
# when STORAGE_PROVIDER=local. Not used when STORAGE_PROVIDER=s3 (default
# for a scaled-out deployment, since local disk storage does not survive
# container replacement and is not shared across replicas/workers).
RUN mkdir -p /app/storage && chown -R node:node /app

USER node

EXPOSE 3000

ENTRYPOINT ["tini", "--"]
CMD ["node_modules/.bin/next", "start"]
