export const WORKFLOW_CONFIG = {
  // Server-side absolute hard limits (override user configuration)
  SERVER_ABSOLUTE_MAX_NODES: 100,
  SERVER_ABSOLUTE_MAX_EDGES: 150,
  SERVER_ABSOLUTE_MAX_EXECUTION_STEPS: 200,
  SERVER_ABSOLUTE_MAX_LOOP_ITERATIONS: 20,
  SERVER_ABSOLUTE_MAX_CONCURRENT_NODES: 5,
  SERVER_ABSOLUTE_NODE_TIMEOUT_MS: 30000,
  SERVER_ABSOLUTE_RUN_TIMEOUT_MS: 300000,
  SERVER_ABSOLUTE_MAX_LLM_CALLS: 30,
  SERVER_ABSOLUTE_MAX_WEB_SEARCHES: 10,
  SERVER_ABSOLUTE_MAX_DOCUMENT_RETRIEVALS: 20,
  SERVER_ABSOLUTE_MAX_OUTPUT_BYTES: 10485760, // 10 MB
  SERVER_ABSOLUTE_MAX_RETRIES: 2,

  CACHE_TTL_SECONDS: 600, // 10 minutes
  DEFAULT_MAX_RETRIES: 2
};
