export const STUDY_CONFIG = {
  MAX_TOPICS_PER_SESSION: 12,
  MAX_QUESTIONS_PER_SESSION: 50,
  MAX_OPTIONS_PER_MCQ: 5,
  MAX_HINTS_PER_QUESTION: 3,
  DEFAULT_DURATION_MINUTES: 30,
  LOW_MASTERY_THRESHOLD: 50.0,
  HIGH_MASTERY_THRESHOLD: 80.0,
  MAX_GENERATION_RETRIES: 2,
  RATE_LIMIT_PER_MINUTE: 30,
  CACHE_TTL_SECONDS: 1800
};
